### ISSUE TITLE
KeyError: 'Tag Blocks does not exist'

### ISSUE THREAD

**Issue by seb303** [twalford/schem-slicer#3]
I'm having trouble getting this to work.

It gets as far as "generating images..." then dumps the usage info:
```
image width: 784
image height: 752
axis: y
do crop: False
do flip: False
do numbering: False
do grid False
generating images...

Usage: run.py path axis [options]
...
```

If I edit run.py so it actually shows the error rather than blindly printing strHelp in the exception handler, then I see this error:

```
Traceback (most recent call last):
  File "C:\Utils\schem-slicer-master\run.py", line 474, in <module>
    main()
  File "C:\Utils\schem-slicer-master\run.py", line 400, in main
    id = infile['Blocks'][arrayPos]
  File "C:\Users\seb\AppData\Local\Programs\Python\Python310\lib\site-packages\nbt\nbt.py", line 543, in __getitem__
    raise KeyError("Tag %s does not exist" % key)
KeyError: 'Tag Blocks does not exist'
```
Not familiar with nbt, so no idea why this might be happening.  Any help would be much appreciated.

**Comment by seb303** [comment]
To answer my own question....
Schematics saved in newer Minecraft versions store the block data in NBT tag 'BlockData' rather than 'Blocks' and 'Data'.

I've created a new version which supports the BlockData tag.

[Pull request](https://github.com/twalford/schem-slicer/pull/4) is pending. In the meantime the new version [can be download here](https://github.com/seb303/schem-slicer).
